TrajectoryPlannerROS:
# Robot Configuration Parameters
  acc_lim_x:                    10.0
  acc_lim_y:                    0.0
  acc_lim_th:                   3.5
  max_vel_x:                    0.8
  min_vel_x:                    0.1
  max_rotational_vel:           0.5
  min_in_place_vel_theta:  0.1
  escape_vel:                   -0.3
  holonomic_robot:              false
  
# The following parameters are only used if holonomic_robot is set to true:
  y_vels: [-0.3, -0.1, 0.1, 0.3]
  
# Goal Tolerance Parameters
  yaw_goal_tolerance:           0.10
  xy_goal_tolerance:            0.10
  latch_xy_goal_tolerance:      true
  
# Forward Simulation Parameters
  sim_time:                     4.0
  sim_granularity:              1
  angular_sim_granularity:      0.05
  vx_samples:                   20
  vtheta_samples:               40
#  controller_frequency:         20 # set above
  
# Trajectory Scoring Parameters
  meter_scoring:                true
#  path_distance_bias:           0.5
#  goal_distance_bias:           2.5
  occdist_scale:                0.1
  heading_lookahead:            0.5
  heading_scoring:              true
  heading_scoring_timestep:     0.8
  dwa:                          true
  publish_cost_grid_pc:         false
  global_frame_id:              /Pioneer3AT/odom
  
# Oscillation Prevention Parameters
  oscillation_reset_dist:       0.1
  
# Global Plan Parameters
  prune_plan:                   true

