recovery_behaviors: [{
    name: conservative_reset, 
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery1,
    type: rotate_recovery/RotateRecovery
  }, {
    name: aggressive_reset,
    type: clear_costmap_recovery/ClearCostmapRecovery,
    reset_distance: 0.1
  }, {
    name: rotate_recovery2,
    type: rotate_recovery/RotateRecovery
  }]

controller_frequency: 10

planner_patience: 5.0

controller_patience: 15.0

#max_planning_retries: 15
