# Odometry motion model parameters. See "Probabilistic Robotics (2005)" or
# http://130.243.105.49/Research/mro/courses/probrob/2012/handouts_03.pdf
alpha_1: 0.1  # meters/meter
alpha_2: 0.1 # meters/degree
alpha_3: 0.1   # degrees/meter
alpha_4: 0.1  # degrees/degree

# Voxel grid size, in meters
voxel_grid_size: 0.00025

# ICP PARAMETERS
max_correspondence_distance: 0.2 
max_iterations: 2000
ransac_iterations: 2000
ransac_outlier_threshold: 0.1
icp_score_scale: 600.0
icp_optimization_epsilon: 0.000001

# Initial position and uncertainty
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0

initial_cov_xx: 0.05
initial_cov_yy: 0.05
initial_cov_aa: 0.05

# How long should the robot move before we run the update step
update_min_d: 0.001
update_min_a: 0.001

# If false, the map is requested via service
use_map_topic: false
first_map_only: true

# The loop rate, adjust based on the frequency of your scanner
spin_rate: 50

# For visualization purposes
covariance_marker_scale: 2
